[package]
name = "stm32_rgb_blink"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt = "0.2"
cortex-m = { version = "^0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.2"
stm32-hal2 = { package = "stm32-hal2", version = "^1.5.5", features = ["l552", "l5rt"] }